Repository Geffrerson7/Proyecto-Unidad-8-Back, pull requests merged in 2023-02, with the labels that each got.

#8 Add order-detail crud
  src/components/index.ts
  src/components/order-detail/controller.ts
  src/components/order-detail/index.ts
  src/router/index.ts
Labels: feature

#15 chore(categories): Improvement in the CRUD of the category component
  prisma/schema.prisma
  src/components/category/controller.ts
Labels: feature

#16 Test: Tests a los endpoints del componente categorias
  babel.config.js
  jest.config.ts
  package.json
  test/category/createCategory.test.ts
  test/category/deleteCategory.test.ts
  test/category/getOneCategory.test.ts
  test/category/listcategories.test.ts
  test/category/updateCategory.test.ts
Labels: Test

#18 chore: Implementacion del datasource-prisma
  src/components/category/controller.ts
  src/components/clients/controller.ts
  src/components/order-detail/controller.ts
  src/components/orders/controller.ts
  src/components/suppliers/controller.ts
  src/components/user/controller.ts
Labels: refactor

#22 Feature/sms twilio
  package.json
  src/components/products/controller.ts
  src/router/index.ts
  src/services/index.ts
  src/services/twilio/index.ts
Labels: feature

#23 Test: add test for order
  package.json
  test/orders/deleteOrder.test.ts
  test/orders/getOneOrder.test.ts
  test/orders/listOrders.test.ts
Labels: feature, Test
